"""shop discovery tables

Revision ID: 1cd5812c08c3
Revises: 098e94116a7b
Create Date: 2026-07-19 13:55:37.840190

"""

import sqlalchemy as sa

from alembic import op

revision = "1cd5812c08c3"
down_revision = "098e94116a7b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'NEW_SHOP_FOUND'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discovery_hunts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game", sa.Enum("POKEMON", "ONE_PIECE", name="game"), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("channels", sa.JSON(), nullable=False),
        sa.Column("priority", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("discovery_hunts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_discovery_hunts_enabled"), ["enabled"], unique=False)
        batch_op.create_index(batch_op.f("ix_discovery_hunts_game"), ["game"], unique=False)

    op.create_table(
        "discovered_sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("game", sa.Enum("POKEMON", "ONE_PIECE", name="game"), nullable=False),
        sa.Column("hunt_id", sa.Integer(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("verdict", sa.String(length=20), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("checks", sa.JSON(), nullable=False),
        sa.Column("first_seen", sa.DateTime(), nullable=False),
        sa.Column("notified", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["hunt_id"], ["discovery_hunts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain"),
    )
    with op.batch_alter_table("discovered_sites", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_discovered_sites_first_seen"), ["first_seen"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("discovered_sites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_discovered_sites_first_seen"))

    op.drop_table("discovered_sites")
    with op.batch_alter_table("discovery_hunts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_discovery_hunts_game"))
        batch_op.drop_index(batch_op.f("ix_discovery_hunts_enabled"))

    op.drop_table("discovery_hunts")
    # ### end Alembic commands ###
