"""product scanner tables

Revision ID: 62671faf0364
Revises: 84a86f583557
Create Date: 2026-07-19 07:22:24.280513

"""
import sqlalchemy as sa

from alembic import op

revision = '62671faf0364'
down_revision = '84a86f583557'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game', sa.Enum('POKEMON', 'ONE_PIECE', name='game'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('exclude_keywords', sa.JSON(), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('use_playwright', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('baseline_done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_scans_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_scans_game'), ['game'], unique=False)

    op.create_table('scan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_key', sa.String(length=500), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['product_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'url_key', name='uq_scan_item')
    )
    with op.batch_alter_table('scan_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_items_first_seen'), ['first_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_items_scan_id'), ['scan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_items_scan_id'))
        batch_op.drop_index(batch_op.f('ix_scan_items_first_seen'))

    op.drop_table('scan_items')
    with op.batch_alter_table('product_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_scans_game'))
        batch_op.drop_index(batch_op.f('ix_product_scans_enabled'))

    op.drop_table('product_scans')
    # ### end Alembic commands ###
