"""initial schema

Revision ID: 84a86f583557
Revises:
Create Date: 2026-07-18 11:06:04.639756

"""

import sqlalchemy as sa

from alembic import op

revision = "84a86f583557"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "notifier_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("routes", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "set_news",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game", sa.Enum("POKEMON", "ONE_PIECE", name="game"), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("set_name", sa.String(length=255), nullable=True),
        sa.Column("region", sa.String(length=32), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("preorder_date", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("guid", sa.String(length=500), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ANNOUNCED", "PREORDER", "RELEASED", name="newsstatus"),
            nullable=False,
        ),
        sa.Column("first_seen", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("announced_notified", sa.Boolean(), nullable=False),
        sa.Column("preorder_notified", sa.Boolean(), nullable=False),
        sa.Column("release_soon_notified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "guid", name="uq_news_source_guid"),
    )
    with op.batch_alter_table("set_news", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_set_news_first_seen"), ["first_seen"], unique=False)
        batch_op.create_index(batch_op.f("ix_set_news_game"), ["game"], unique=False)
        batch_op.create_index(batch_op.f("ix_set_news_source"), ["source"], unique=False)

    op.create_table(
        "watches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game", sa.Enum("POKEMON", "ONE_PIECE", name="game"), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("retailer", sa.String(length=120), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("adapter", sa.String(length=80), nullable=True),
        sa.Column("detection", sa.JSON(), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("cooldown_seconds", sa.Integer(), nullable=False),
        sa.Column("channels", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("listing_seen", sa.Boolean(), nullable=False),
        sa.Column("notify_on_first_seen", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_check_at", sa.DateTime(), nullable=True),
        sa.Column(
            "last_status",
            sa.Enum("IN_STOCK", "OUT_OF_STOCK", "UNKNOWN", name="stockstatus"),
            nullable=False,
        ),
        sa.Column("last_price", sa.Float(), nullable=True),
        sa.Column("last_currency", sa.String(length=8), nullable=True),
        sa.Column("last_title", sa.Text(), nullable=True),
        sa.Column("last_image_url", sa.Text(), nullable=True),
        sa.Column("last_buy_url", sa.Text(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_in_stock_at", sa.DateTime(), nullable=True),
        sa.Column("last_notified_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("watches", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_watches_enabled"), ["enabled"], unique=False)
        batch_op.create_index(batch_op.f("ix_watches_game"), ["game"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "NEW_LISTING",
                "BACK_IN_STOCK",
                "NEW_SET_ANNOUNCED",
                "PREORDER_LIVE",
                "RELEASE_SOON",
                "TEST",
                name="eventtype",
            ),
            nullable=False,
        ),
        sa.Column("notifier", sa.String(length=120), nullable=False),
        sa.Column("notifier_type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("watch_id", sa.Integer(), nullable=True),
        sa.Column("news_id", sa.Integer(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["news_id"], ["set_news.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["watch_id"], ["watches.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_event_type"), ["event_type"], unique=False
        )

    op.create_table(
        "stock_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("watch_id", sa.Integer(), nullable=False),
        sa.Column("checked_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("IN_STOCK", "OUT_OF_STOCK", "UNKNOWN", name="stockstatus"),
            nullable=False,
        ),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["watch_id"], ["watches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stock_checks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stock_checks_checked_at"), ["checked_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_stock_checks_watch_id"), ["watch_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stock_checks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stock_checks_watch_id"))
        batch_op.drop_index(batch_op.f("ix_stock_checks_checked_at"))

    op.drop_table("stock_checks")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_event_type"))
        batch_op.drop_index(batch_op.f("ix_notifications_created_at"))

    op.drop_table("notifications")
    with op.batch_alter_table("watches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watches_game"))
        batch_op.drop_index(batch_op.f("ix_watches_enabled"))

    op.drop_table("watches")
    with op.batch_alter_table("set_news", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_set_news_source"))
        batch_op.drop_index(batch_op.f("ix_set_news_game"))
        batch_op.drop_index(batch_op.f("ix_set_news_first_seen"))

    op.drop_table("set_news")
    op.drop_table("notifier_configs")
    op.drop_table("api_tokens")
    # ### end Alembic commands ###
